### ISSUE TITLE
Transmit demo program doesn't work on NVIDIA Jetson

### ISSUE THREAD

**Issue by pierreSCpapon** [opendroneid/transmitter-linux#1]
Transmit demo program doesn't work on NVIDIA Jetson similar to the RPI issue described in the README:

> NOTE: When tested, the beacon transmit only partly worked on Raspberry Pi 3 and 4. The pre-defined single location message that can be uncommented in the beacon.conf file works okay. However, any data that the transmit program tries to write to the host ap daemon does not appear to be used. It is not clear why this is so.

Spec:

> NVIDIA Jetson TX2
 L4T 32.6.1 [ JetPack 4.6 ]
   Ubuntu 18.04.6 LTS
   Kernel Version: 4.9.253-tegra
 CUDA 10.2.300
   CUDA Architecture: 6.2
 OpenCV version: 4.1.1
   OpenCV Cuda: NO
 CUDNN: 8.2.1.32
 TensorRT: 8.0.1.6
 Vision Works: 1.6.0.501
 VPI: ii libnvvpi1 1.1.12 arm64 NVIDIA Vision Programming Interface library
 Vulcan: 1.2.70

On the Jetson, I can confirm this also works: The pre-defined single location message that can be uncommented in the beacon.conf file works okay.

Using a USB WiFi card as the built-in WiFi interface wont work with hostapd
On the Jetson, it seems to be a common issue, the AP seems to be running fine but no WiFi network is actually created. The USB WiFi dongle fixed this.

I am happy to do some testing and provide feedback.

**Comment by friissoren** [comment]
Interesting. I don't have any Jetson HW, so I unfortunately won't be able to help solve this. However, it is likely that there are similar root-causes for the problems on both RPi and Jetson HW.

Using a USB Wi-Fi dongle was something I had not thought of earlier. I will try that on the RPi HW whenever I find the time.

**Comment by pierreSCpapon** [comment]
Running the `sudo ./transmit b p` with `sudo hostapd/hostapd/hostapd beacon.conf` in a separate shell runs for a while but eventually returns: `Return value from ap_interface_init: 0`. It runs but doesnt show up on the Android App.

Perhaps a useful clue?

Log:
`Reminder: Wi-Fi Beacon only works when running
"sudo hostapd/hostapd/hostapd beacon.conf" in a separate shell.
hostapd_cli v2.9
Copyright (c) 2004-2019, Jouni Malinen <j@w1.fi> and contributors
This software may be distributed under the terms of the BSD license.
See README for more details.
Selected interface 'wlan0'
SET vendor_elements ddE9FA0BBC0D00F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D01F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D02F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D03F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D04F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D05F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D06F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D07F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D08F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
SET vendor_elements ddE9FA0BBC0D09F1190901123131323632343135304139304533414531454330000000014246443334353442373738453536354332344237300000001126B500005816AF1E38CDFFFF9808AC0870084A63150E01002110023F003FAB0131323334353637383930313233343536372111313233343536373839303132333435363738393031323321123132333435363738393031323334353637383930313233310044726F6E65204944207465737420666C696768742D2D2D4104683DAF1E28A6FFFF010000D007D00712F9070000000000510046494E38376173747264676531326B3800000000000000. Result: OK
Return value from ap_interface_init: 0`

**Comment by qs-estebanb** [comment]
> FA0BBC0D

Hi!
Have you tried putting one of those vendor elements in the beacon.conf file ?
In my experience the dynamic information that I provide to the hostapd_cli was not being updated properly, but when I set the vendor elements in the beacon.conf it was working.

In my case the information was not being updated because I was running the hostpad inside a docker container and the host was also using the wifi card, generating unexpected behaves.

Have you checked if other software is also configurating the card (something like wpa_supplicant or whatever you are using in your Jetson) ?

**Comment by pierreSCpapon** [comment]
OK, I finally got to the bottom of it. I am able to get the transmit demo program working properly on the Jetson.
I had to do two things:

1. Use a USB WiFi interface. I was not able to use Jetson's built-in Broadcom BCM4354 to start a working AP using `hostapd` even using a generic `beacon.conf`. With the USB WiFi interface I was able to create an AP using `hostapd` and use a static vendor element. This would show up on the Android app.
2. In `wifi_beacon.c` the function `send_update_beacon();` was commented out but turned out to be necessary at least on the Jetson. This enabled me to run the transmit demo program to generate and update the vendor element dynamically.
```
    // It doesn't appear to be necessary to send the update_beacon cmd?
    //send_update_beacon();
    //sleep(1);
```

@friissoren  It would be interesting to see if that fixes the RaspberryPi issues. Unfortunately, I do not have one here to test.

**Comment by friissoren** [comment]
Great. This is very nice to know. I commented out the update-beacon command since it didn't seem to make any difference on the Z490 motherboard and then when I was testing on the RPi HW I forgot about it. There seems to be differences in the driver implementations between different HW platforms (not surprisingly).

I will try it on the RPi HW at some point but it might take a while before I find a spare moment to set things up again.

I am a bit surprised that you weren't able to get the built-in Wi-Fi transmitter in AP mode. Did you disconnect it from/make it forget all other Wi-Fi networks before trying? That part at least was working fine on the RPi (well, that obviously doesn't say anything about how Jetson HW behaves :-)

**Comment by friissoren** [comment]
I tested on Raspberry Pi 3B HW, with the new Pi OS 11 Bullseye SW release. 
Enabling the "update beacon" command did help. However, only when sending single messages. Using message packs still fails. There must be some size restriction in the Wi-Fi driver implementation for vendor specific information element data.
I will update the code and documentation.
