### ISSUE TITLE
option l on Raspberry Pi 3B+ returned error

### ISSUE THREAD

**Issue by Risker1210** [opendroneid/transmitter-linux#10]
Hi,

My device is Raspberry Pi 3B+ with Debian 11 (bullseye).
I know that `option 4` and `option 5 p` are not supported according to the readme.
But when I do `sudo ./transmit l` I still got errors below:
```
Command 0xA returned error 0xC
Command 0x39 returned error 0x1
Supported Low Energy Bluetooth features:
        Features: 0x3f 0x00 0x00 0x08 0x00 0x00 0x00 0x00
          LE Encryption
          Connection Parameter Request Procedure
          Extended Reject Indication
          Slave-initiated Features Exchange
          LE Ping
          LE Data Packet Length Extension
          Remote Public Key Validation
Command 0x39 returned error 0x1
``` 
how can I fix it? 

thanks.

**Comment by friissoren** [comment]
I tried again on a RPi 4 with Debian 11. When transmitting Bluetooth, there is no need to start the hostapd server so it is enough to just compile the stuff and then run "sudo build/transmit l". You seem to have succeeded with that.

The error log you have pasted is the same that I see when I run it. I.e. this can be considered normal behavior.

Did you have the receiver app running on a phone at the same time? It should have picked up the signals?

(Please note that the content of all the individual messages is hard-coded and does not change. I.e. you won't see any trail of the drone on the map showing it to move around. Press the Info button in the app if the drone shows up).

**Comment by Risker1210** [comment]
Oh, I see.
I installed DroneScanner on my iPhone after I saw your reply, and it can receive the signals now. 
Thank you!
