### ISSUE TITLE
error) download and setup in transmitter-linux 

### ISSUE THREAD

**Issue by superBaik** [opendroneid/transmitter-linux#7]
Hi there ,
Thanks for your effort and code.

I am trying to set up the transmitter-linux both my linux labtop and raspberrypi .

1. I think the only way to clone the code is using "https: 
  - trying to ssh, but I cant use it . 
  - the error is 
  Permission denied (public key) , 
  
  even though I ve uploaded my public key in github, i couldnt access 

 - so I tried to clone use https only, 
 then I figured out the three submodule(folder) such as "bluez" "core-c" "hostapd"  are cannot be downloaded properly. 

2. Is there anyway to clone by https? 

3. On your README, you may suggest clone using ssh, but ssh cannot be worked. 
4. furthermore, I couldnt do  
 - git submodule update --init 
and Make commander,  ( becuase any folder or file to make -j4, if download by https protocol ) 

I hope that you can reply with my issues, 
Thanks in advance !

**Comment by friissoren** [comment]
The code of the repository can be cloned via either https or ssh:
https: https://github.com/opendroneid/transmitter-linux.git
ssh: git@github.com:opendroneid/transmitter-linux.git

Only the ssh method require you to have your ssh key stored in the Github settings.

The [submodules](https://github.com/opendroneid/transmitter-linux/blob/main/.gitmodules) are currently all setup to use the ssh method.

If that is causing issues for you (e.g. only the http/https access method works), it should be possible to add lines in your `.gitconfig` file, to change the access method. I didn't test this but it might help you?

```
    [url " http://w1.fi/hostap.git"]
      insteadOf=git://w1.fi/hostap.git
    [url "https://git.kernel.org/pub/scm/bluetooth/bluez.git"]
      insteadOf=git://git.kernel.org/pub/scm/bluetooth/bluez.git
    [url "https://github.com/opendroneid/opendroneid-core-c.git"]
      insteadOf=git@github.com:opendroneid/opendroneid-core-c.git
```

**Comment by planewave** [comment]
you need to add a new SSH key to your GitHub account. it works for me
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by superBaik** [comment]
THANKS FOR your reply 

Anyway, 
I might understand about connecting and setting ssh key with Github account. 

I think I have already down about it. 

and also I understand the submodule can be automatically downloaded when using ssh.
thats why I tried the ssh method not https.

But still I have in trouble..... 
I dont know why....
please help me .
![sad](https://user-images.githubusercontent.com/25325269/193176876-fa4d6efe-9c1d-4e45-acd6-3c375145b1bb.PNG)

I checked my ssh key and github account was connected through  
`ssh -T git@github.com`

Am I wrong ? or is there anything else I didnt understand ...?

**Comment by friissoren** [comment]
I got an email with some additional info from you. A couple of comments on that:

Do not use sudo when you do the git clone.

Make sure your private and public ssh keys on your own PC have the correct access permission. Use `chmod 600 <your key name>` on the files. Also, ensure that they are not owned by root, but by your own user name.

**Comment by superBaik** [comment]
Thank you very much !! @planewave I did what you mentioned, and also @friissoren I works for me. 

I think the best solution is that, 

1. download thru https 
2. edit gitconfig file 
3. chmod 600 <your key name> 

stage number3 was kinda problem for me 

thanks again. 

I think I can  study and research using Raspberrypi(linux) remoteid transmitter deeply.
